In [1]:
import numpy as np

In [30]:
AA= [[1,-1,-1,1], [2,0,2,0],[0,-1,-2,0],[3,-3,-2,4]]
AA = np.array(AA).astype(np.float_)

B =  np.random.randint(0, 64, (10,10)).astype(np.float_)


C = [[-7,  1 , 5 ,-1],
 [-2 ,-4,  4 , 5],
 [ 3 , 4 , 1, -1]]

C = np.array(C).astype(np.float_)

D =  np.array([[1,4,9],
               [16,25,36],
               [49,64,81]]).astype(np.float_)

In [3]:
def gaussEli(Y):
    A = Y.copy()
    
    findaswap =  False
    j = 0
    

    #for i in range(A.shape[0] - 1):
    for i in range(0,A.shape[0]):
       


            if A[i,i] == 0:
                for n in range(i+1, A.shape[0]):
                    if A[n,i] != 0:
                        findaswap == True
                        A[[i, n]] = A[[n, i]]

                        break

                    if findaswap == False :
                        print ("elimination not possible")
                        #print(A)
                        #print(i)
                        return 






            for k in range(i+1, A.shape[0]):
                



                A[k] = A[k] - (A[k,i]/A[i,i])*A[i]
                print(A)

              
                    
    return A
                    



In [4]:
def isrref(X):
    

        
    return isrref_
         
    

In [5]:
isrref(D)

False

In [27]:
def gaussJordanEli(X):
    A = X.copy()
    
    findaswap =  False
    j = 0
    

    for i in range(0, A.shape[0]):
        

            
       


        if A[i,i] == 0:
            
            for n in range(i+1, A.shape[0]):
                if A[n,i] != 0:
                    findaswap == True
                    A[[i, n]] = A[[n, i]]

                    break

                if findaswap == False :
                    print ("elimination not possible")

                    return 



        if A[i,i] == 0:
            return A

        A[i] = A[i]/A[i,i]
        
        
        
        for k in range(0, A.shape[0]):
            
         
           

            if k == i:
                continue

           
            

            A[k] = A[k] - (A[k,i]/A[i,i])*A[i]
          

              
                    
    return A
                    



In [ ]:
class Matrixx(np.matrix):
    def eli(self):
        return gaussEli(self)
    
    
        
        
    

In [31]:
gaussJordanEli(D)

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [32]:
gaussEli(D)

[[   1.    4.    9.]
 [   0.  -39. -108.]
 [  49.   64.   81.]]
[[   1.    4.    9.]
 [   0.  -39. -108.]
 [   0. -132. -360.]]
[[   1.            4.            9.        ]
 [   0.          -39.         -108.        ]
 [   0.            0.            5.53846154]]


array([[   1.        ,    4.        ,    9.        ],
       [   0.        ,  -39.        , -108.        ],
       [   0.        ,    0.        ,    5.53846154]])