In [1]:
import numpy as np

In [2]:
A= [[1,-1,-1,1], [2,0,2,0],[0,-1,-2,0],[3,-3,-2,4]]
A = np.array(A).astype(np.float_)

B =  np.random.randint(0, 64, (5,5)).astype(np.float_)


C = [[-7,  1 , 5 ,-1],
 [-2 ,-4,  4 , 5],
 [ 3 , 4 , 1, -1]]

C = np.array(C).astype(np.float_)

D =  np.array([[1,4,9],
               [16,25,36],
               [49,64,81]]).astype(np.float_)

In [4]:
# without partial ivoting

U =  D.copy()
L = np.identity(3)

n = 3

for j in range(0, n-1):
    for i in range(j+1, n):
        L[i,j] = U[i,j]/U[j,j]
        
        for k in range(j,n):
            U[i,k] = U[i,k] - L[i,j]*U[j,k]

In [11]:
#crude implementation with partial ivoting


n = 3
U =  D.copy()
L = np.identity(n)
P = np.identity(n)




def rowExchange(X, m, n, j, k):
    
    
    
    row  = X[m,j: k].copy()
    X[m, j:k] = X[n, j:k]
    X[n, j:k] =  row
    
    return X
    
    

for j in range(0, n-1):
    
    idx =  np.argmax(abs(U[:,j]))
    
    if idx >= j:
        U = rowExchange(U, idx,j,j, n)
        L = rowExchange(L, idx, j,1,j-1)
        P = rowExchange(P, idx, j, 0, n)
    
    
    for i in range(j+1, n):
        L[i,j] = U[i,j]/U[j,j]
        
        for k in range(j,n):
            U[i,k] = U[i,k] - L[i,j]*U[j,k]

In [12]:
L

array([[1.        , 0.        , 0.        ],
       [0.32653061, 1.        , 0.        ],
       [0.02040816, 0.65671642, 1.        ]])

In [13]:
U

array([[4.90000000e+01, 6.40000000e+01, 8.10000000e+01],
       [1.77635684e-15, 4.10204082e+00, 9.55102041e+00],
       [1.11022302e-16, 0.00000000e+00, 1.07462687e+00]])

In [14]:
D #D = LU

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

In [17]:
P@L@U

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])